/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { BillingCreateNestedManyWithoutClientsInput } from "./BillingCreateNestedManyWithoutClientsInput";
import { Type } from "class-transformer";
import { InvoiceCreateNestedManyWithoutClientsInput } from "./InvoiceCreateNestedManyWithoutClientsInput";
import { NotificationCreateNestedManyWithoutClientsInput } from "./NotificationCreateNestedManyWithoutClientsInput";

@InputType()
class ClientCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => BillingCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => BillingCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => BillingCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  billings?: BillingCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  birthday?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => InvoiceCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  invoices?: InvoiceCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutClientsInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutClientsInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;
}

export { ClientCreateInput as ClientCreateInput };
