/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { BillingUpdateManyWithoutClientsInput } from "./BillingUpdateManyWithoutClientsInput";
import { Type } from "class-transformer";
import { InvoiceUpdateManyWithoutClientsInput } from "./InvoiceUpdateManyWithoutClientsInput";
import { NotificationUpdateManyWithoutClientsInput } from "./NotificationUpdateManyWithoutClientsInput";

@InputType()
class ClientUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => BillingUpdateManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => BillingUpdateManyWithoutClientsInput)
  @IsOptional()
  @Field(() => BillingUpdateManyWithoutClientsInput, {
    nullable: true,
  })
  billings?: BillingUpdateManyWithoutClientsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  birthday?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceUpdateManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceUpdateManyWithoutClientsInput)
  @IsOptional()
  @Field(() => InvoiceUpdateManyWithoutClientsInput, {
    nullable: true,
  })
  invoices?: InvoiceUpdateManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationUpdateManyWithoutClientsInput,
  })
  @ValidateNested()
  @Type(() => NotificationUpdateManyWithoutClientsInput)
  @IsOptional()
  @Field(() => NotificationUpdateManyWithoutClientsInput, {
    nullable: true,
  })
  notifications?: NotificationUpdateManyWithoutClientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;
}

export { ClientUpdateInput as ClientUpdateInput };
